swagger: '2.0'
info:
  description: This is a sample API
  version: 1.0.0
  title: ${classPrefix} API

  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

# tags are used for organizing operations
tags:
- name: admins
  description: Secured Admin-only calls
- name: developers
  description: Operations available to regular developers
schemes:
- http

paths:
  /sample:
    get:
      tags:
        - ${classPrefix}

      summary: Gets a sample
      operationId: getSample
      produces:
      - application/json

      responses:
        200:
          description: Success
          schema:
            $ref: '#/definitions/Sample'

        404:
          description: Not Found

definitions:
  Sample:
    type: object
    required:
    - id
    - name

    properties:
      id:
        type: integer
        format: int64
        example: 23131296320

      name:
        type: string
        example: Sample item name

